//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_SOP.HRYNSR {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.224.52.12:2002/", ConfigurationName="HRYNSR.YNSafetySoap")]
    public interface YNSafetySoap {
        
        // CODEGEN: Generating message contract since message UserValidateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://10.224.52.12:2002/UserValidate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HR_SOP.HRYNSR.UserValidateResponse UserValidate(HR_SOP.HRYNSR.UserValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.224.52.12:2002/UserValidate", ReplyAction="*")]
        System.Threading.Tasks.Task<HR_SOP.HRYNSR.UserValidateResponse> UserValidateAsync(HR_SOP.HRYNSR.UserValidateRequest request);
        
        // CODEGEN: Generating message contract since message GetEmpInfo_DtRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://10.224.52.12:2002/GetEmpInfo_Dt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HR_SOP.HRYNSR.GetEmpInfo_DtResponse GetEmpInfo_Dt(HR_SOP.HRYNSR.GetEmpInfo_DtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.224.52.12:2002/GetEmpInfo_Dt", ReplyAction="*")]
        System.Threading.Tasks.Task<HR_SOP.HRYNSR.GetEmpInfo_DtResponse> GetEmpInfo_DtAsync(HR_SOP.HRYNSR.GetEmpInfo_DtRequest request);
        
        // CODEGEN: Generating message contract since message GetEmpInfo_JsonRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://10.224.52.12:2002/GetEmpInfo_Json", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HR_SOP.HRYNSR.GetEmpInfo_JsonResponse GetEmpInfo_Json(HR_SOP.HRYNSR.GetEmpInfo_JsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.224.52.12:2002/GetEmpInfo_Json", ReplyAction="*")]
        System.Threading.Tasks.Task<HR_SOP.HRYNSR.GetEmpInfo_JsonResponse> GetEmpInfo_JsonAsync(HR_SOP.HRYNSR.GetEmpInfo_JsonRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.224.52.12:2002/")]
    public partial class SoapHead : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserValidate", WrapperNamespace="http://10.224.52.12:2002/", IsWrapped=true)]
    public partial class UserValidateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://10.224.52.12:2002/")]
        public HR_SOP.HRYNSR.SoapHead SoapHead;
        
        public UserValidateRequest() {
        }
        
        public UserValidateRequest(HR_SOP.HRYNSR.SoapHead SoapHead) {
            this.SoapHead = SoapHead;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserValidateResponse", WrapperNamespace="http://10.224.52.12:2002/", IsWrapped=true)]
    public partial class UserValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.224.52.12:2002/", Order=0)]
        public bool UserValidateResult;
        
        public UserValidateResponse() {
        }
        
        public UserValidateResponse(bool UserValidateResult) {
            this.UserValidateResult = UserValidateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpInfo_Dt", WrapperNamespace="http://10.224.52.12:2002/", IsWrapped=true)]
    public partial class GetEmpInfo_DtRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://10.224.52.12:2002/")]
        public HR_SOP.HRYNSR.SoapHead SoapHead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.224.52.12:2002/", Order=0)]
        public string empNo;
        
        public GetEmpInfo_DtRequest() {
        }
        
        public GetEmpInfo_DtRequest(HR_SOP.HRYNSR.SoapHead SoapHead, string empNo) {
            this.SoapHead = SoapHead;
            this.empNo = empNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpInfo_DtResponse", WrapperNamespace="http://10.224.52.12:2002/", IsWrapped=true)]
    public partial class GetEmpInfo_DtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.224.52.12:2002/", Order=0)]
        public System.Data.DataTable GetEmpInfo_DtResult;
        
        public GetEmpInfo_DtResponse() {
        }
        
        public GetEmpInfo_DtResponse(System.Data.DataTable GetEmpInfo_DtResult) {
            this.GetEmpInfo_DtResult = GetEmpInfo_DtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpInfo_Json", WrapperNamespace="http://10.224.52.12:2002/", IsWrapped=true)]
    public partial class GetEmpInfo_JsonRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://10.224.52.12:2002/")]
        public HR_SOP.HRYNSR.SoapHead SoapHead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.224.52.12:2002/", Order=0)]
        public string empNo;
        
        public GetEmpInfo_JsonRequest() {
        }
        
        public GetEmpInfo_JsonRequest(HR_SOP.HRYNSR.SoapHead SoapHead, string empNo) {
            this.SoapHead = SoapHead;
            this.empNo = empNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpInfo_JsonResponse", WrapperNamespace="http://10.224.52.12:2002/", IsWrapped=true)]
    public partial class GetEmpInfo_JsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.224.52.12:2002/", Order=0)]
        public string GetEmpInfo_JsonResult;
        
        public GetEmpInfo_JsonResponse() {
        }
        
        public GetEmpInfo_JsonResponse(string GetEmpInfo_JsonResult) {
            this.GetEmpInfo_JsonResult = GetEmpInfo_JsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface YNSafetySoapChannel : HR_SOP.HRYNSR.YNSafetySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YNSafetySoapClient : System.ServiceModel.ClientBase<HR_SOP.HRYNSR.YNSafetySoap>, HR_SOP.HRYNSR.YNSafetySoap {
        
        public YNSafetySoapClient() {
        }
        
        public YNSafetySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YNSafetySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YNSafetySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YNSafetySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR_SOP.HRYNSR.UserValidateResponse HR_SOP.HRYNSR.YNSafetySoap.UserValidate(HR_SOP.HRYNSR.UserValidateRequest request) {
            return base.Channel.UserValidate(request);
        }
        
        public bool UserValidate(HR_SOP.HRYNSR.SoapHead SoapHead) {
            HR_SOP.HRYNSR.UserValidateRequest inValue = new HR_SOP.HRYNSR.UserValidateRequest();
            inValue.SoapHead = SoapHead;
            HR_SOP.HRYNSR.UserValidateResponse retVal = ((HR_SOP.HRYNSR.YNSafetySoap)(this)).UserValidate(inValue);
            return retVal.UserValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR_SOP.HRYNSR.UserValidateResponse> HR_SOP.HRYNSR.YNSafetySoap.UserValidateAsync(HR_SOP.HRYNSR.UserValidateRequest request) {
            return base.Channel.UserValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR_SOP.HRYNSR.UserValidateResponse> UserValidateAsync(HR_SOP.HRYNSR.SoapHead SoapHead) {
            HR_SOP.HRYNSR.UserValidateRequest inValue = new HR_SOP.HRYNSR.UserValidateRequest();
            inValue.SoapHead = SoapHead;
            return ((HR_SOP.HRYNSR.YNSafetySoap)(this)).UserValidateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR_SOP.HRYNSR.GetEmpInfo_DtResponse HR_SOP.HRYNSR.YNSafetySoap.GetEmpInfo_Dt(HR_SOP.HRYNSR.GetEmpInfo_DtRequest request) {
            return base.Channel.GetEmpInfo_Dt(request);
        }
        
        public System.Data.DataTable GetEmpInfo_Dt(HR_SOP.HRYNSR.SoapHead SoapHead, string empNo) {
            HR_SOP.HRYNSR.GetEmpInfo_DtRequest inValue = new HR_SOP.HRYNSR.GetEmpInfo_DtRequest();
            inValue.SoapHead = SoapHead;
            inValue.empNo = empNo;
            HR_SOP.HRYNSR.GetEmpInfo_DtResponse retVal = ((HR_SOP.HRYNSR.YNSafetySoap)(this)).GetEmpInfo_Dt(inValue);
            return retVal.GetEmpInfo_DtResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR_SOP.HRYNSR.GetEmpInfo_DtResponse> HR_SOP.HRYNSR.YNSafetySoap.GetEmpInfo_DtAsync(HR_SOP.HRYNSR.GetEmpInfo_DtRequest request) {
            return base.Channel.GetEmpInfo_DtAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR_SOP.HRYNSR.GetEmpInfo_DtResponse> GetEmpInfo_DtAsync(HR_SOP.HRYNSR.SoapHead SoapHead, string empNo) {
            HR_SOP.HRYNSR.GetEmpInfo_DtRequest inValue = new HR_SOP.HRYNSR.GetEmpInfo_DtRequest();
            inValue.SoapHead = SoapHead;
            inValue.empNo = empNo;
            return ((HR_SOP.HRYNSR.YNSafetySoap)(this)).GetEmpInfo_DtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR_SOP.HRYNSR.GetEmpInfo_JsonResponse HR_SOP.HRYNSR.YNSafetySoap.GetEmpInfo_Json(HR_SOP.HRYNSR.GetEmpInfo_JsonRequest request) {
            return base.Channel.GetEmpInfo_Json(request);
        }
        
        public string GetEmpInfo_Json(HR_SOP.HRYNSR.SoapHead SoapHead, string empNo) {
            HR_SOP.HRYNSR.GetEmpInfo_JsonRequest inValue = new HR_SOP.HRYNSR.GetEmpInfo_JsonRequest();
            inValue.SoapHead = SoapHead;
            inValue.empNo = empNo;
            HR_SOP.HRYNSR.GetEmpInfo_JsonResponse retVal = ((HR_SOP.HRYNSR.YNSafetySoap)(this)).GetEmpInfo_Json(inValue);
            return retVal.GetEmpInfo_JsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR_SOP.HRYNSR.GetEmpInfo_JsonResponse> HR_SOP.HRYNSR.YNSafetySoap.GetEmpInfo_JsonAsync(HR_SOP.HRYNSR.GetEmpInfo_JsonRequest request) {
            return base.Channel.GetEmpInfo_JsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR_SOP.HRYNSR.GetEmpInfo_JsonResponse> GetEmpInfo_JsonAsync(HR_SOP.HRYNSR.SoapHead SoapHead, string empNo) {
            HR_SOP.HRYNSR.GetEmpInfo_JsonRequest inValue = new HR_SOP.HRYNSR.GetEmpInfo_JsonRequest();
            inValue.SoapHead = SoapHead;
            inValue.empNo = empNo;
            return ((HR_SOP.HRYNSR.YNSafetySoap)(this)).GetEmpInfo_JsonAsync(inValue);
        }
    }
}
